base_resolution: 120
max_extension: 200e3
extres: {20e3: 40, 60e3: 120, 100e3: 240, 300e3: 480}
root: "./"
indir: "./aux/"
dem_path: "/home/sberton2/Lavoro/projects/validate_shadowspy/LDEM_80S_40MPP_ADJ.TIF"
fartopo_path: 'same_dem'
outdir: "./out/"
tmpdir: "./tmp/"
start_time: "2026-01-30 15:00:00.0" # datetime.datetime(2026, 1, 30, hour=15)
end_time: "2026-01-30 17:00:00.0" # datetime.datetime(2026, 1, 30, hour=17)
time_step_hours: 1
bbox_roi: [50e3, -150e3, 150e3, -50e3] # minx, miny, maxx, maxy
download_kernels: false
point_source: true
extsource_coord: "./aux/coordflux_100pts_outline33_centerlast_R1_F1_stdlimbdark.txt"
images_index: "/home/sberton2/Lavoro/projects/validate_shadowspy/final_selection_0_sel0.csv"
#azi_ele_path: "azi_ele_list.in"